name: 📚 Deploy Documentation

on:
  push:
    branches: [main, dev]
    paths: ["docs/**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-docs:
    name: 📚 Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: 📥 Install dependencies
        run: npm ci

      - name: 📚 Build VitePress docs
        run: npm run docs:build

      - name: 🚀 Deploy to Vercel
        # Only deploy from the main repository, not forks
        if: github.repository == 'Shelf-nu/shelf.nu'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./docs/.vitepress/dist
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
